// Auto-generated test fixtures from database analysis.
// Each fixture represents a unique structural pattern found in real data.
//
// Generated by: npx tsx src/unified-api/extract-fixtures.ts

import type { ChatCompletionsEntry } from './chat-types'
import type { ResponsesDataItem } from './responses-types'

export interface Fixture<T> {
	/** The TR data */
	data: T[]
	/** Original TR id in database */
	id: number
	/** Structural pattern signature */
	signature: string
}

export const chatFixtures: Fixture<ChatCompletionsEntry>[] = [
	// [TR #7] openai-chat::content:string | tool_calls:none
	{
		data: [
			{
				content: 'synthetic_text_149',
				role: 'assistant',
			},
		],
		id: 7,
		signature: 'SIG_340',
	},
	// [TR #34] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_150',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_1"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01LP1rfErykf3qmuaWdvkz45',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_151',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01LP1rfErykf3qmuaWdvkz45',
			},
		],
		id: 34,
		signature: 'SIG_341',
	},
	// [TR #13460] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				content: 'synthetic_text_152',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_2"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01G8ykcGrCGSm8egK9J3izKb',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_153',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01G8ykcGrCGSm8egK9J3izKb',
			},
		],
		id: 13460,
		signature: 'SIG_342',
	},
	// [TR #39] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_3"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_013i7qpf3Cp3rUJHRppJ9Q4o',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_154',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_013i7qpf3Cp3rUJHRppJ9Q4o',
			},
		],
		id: 39,
		signature: 'SIG_343',
	},
	// [TR #13465] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_4"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01Xw9HxkTXGSGJudRB8B8wfy',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_155',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Xw9HxkTXGSGJudRB8B8wfy',
			},
		],
		id: 13465,
		signature: 'SIG_344',
	},
	// [TR #7018] openai-chat::content:string | tool_calls:none | reasoning:[reasoning]
	{
		data: [
			{
				content: 'synthetic_text_156',
				reasoning: 'synthetic_text_323',
				role: 'assistant',
			},
		],
		id: 7018,
		signature: 'SIG_345',
	},
	// [TR #7022] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning] → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning: 'synthetic_text_324',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_5"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-85f5697691557581',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_157',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-85f5697691557581',
			},
		],
		id: 7022,
		signature: 'SIG_346',
	},
	// [TR #5521] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_6"}',
							name: 'bash',
						},
						id: 'toolu_bdrk_01894ZnP66afcPfXvLqggtGs',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_158',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01894ZnP66afcPfXvLqggtGs',
			},
		],
		id: 5521,
		signature: 'SIG_347',
	},
	// [TR #5516] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_159',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_7"}',
							name: 'bash',
						},
						id: 'toolu_bdrk_016yGasPHpQZ9FavyaK1Gd6x',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_160',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_016yGasPHpQZ9FavyaK1Gd6x',
			},
		],
		id: 5516,
		signature: 'SIG_348',
	},
	// [TR #13750] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_8"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01SGrj8WXzE433umYEbcuzUS',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_161',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01SGrj8WXzE433umYEbcuzUS',
			},
		],
		id: 13750,
		signature: 'SIG_349',
	},
	// [TR #13462] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_162',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_9"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01Eus8skSbaB4HxtmS4iFbhi',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_163',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Eus8skSbaB4HxtmS4iFbhi',
			},
		],
		id: 13462,
		signature: 'SIG_350',
	},
	// [TR #527] openai-chat::content:null | tool_calls:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: null,
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_10"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01EhtEjNvW5vb8tkfgGs8AFq',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_164',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01EhtEjNvW5vb8tkfgGs8AFq',
			},
		],
		id: 527,
		signature: 'SIG_351',
	},
	// [TR #13741] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_11"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01Ezmre15VYmwushQqete2wJ',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_12"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01R6k37616A6ozPkpp3Tdwp6',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_165',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Ezmre15VYmwushQqete2wJ',
			},
			{
				content: 'synthetic_text_166',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01R6k37616A6ozPkpp3Tdwp6',
			},
		],
		id: 13741,
		signature: 'SIG_352',
	},
	// [TR #13493] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_167',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_13"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01Dmzg6CS2N9JbwiKDuLm9iu',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_14"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_019fdcozS33gaS85PvyzhsJN',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_168',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Dmzg6CS2N9JbwiKDuLm9iu',
			},
			{
				content: 'synthetic_text_169',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_019fdcozS33gaS85PvyzhsJN',
			},
		],
		id: 13493,
		signature: 'SIG_353',
	},
	// [TR #1082] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning_opaque] → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning_opaque: 'OPAQUE_314',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_15"}',
							name: 'send_message',
						},
						id: 'call_MHxtSlhXRUlYckplcjBnM093ejQ',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_170',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'call_MHxtSlhXRUlYckplcjBnM093ejQ',
			},
		],
		id: 1082,
		signature: 'SIG_354',
	},
	// [TR #6034] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_171',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_16"}',
							name: 'web_search',
						},
						id: 'toolu_01AnAT7AJY7WJAtrnLbYUfFr',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_17"}',
							name: 'send_message',
						},
						id: 'toolu_01FxkS82PE8YQTjPZuyXWeJ2',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_172',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01AnAT7AJY7WJAtrnLbYUfFr',
			},
			{
				content: 'synthetic_text_173',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_01FxkS82PE8YQTjPZuyXWeJ2',
			},
		],
		id: 6034,
		signature: 'SIG_355',
	},
	// [TR #1] openai-chat::
	{
		data: [],
		id: 1,
		signature: 'SIG_356',
	},
	// [TR #7789] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_18"}',
							name: 'bash',
						},
						id: 'toolu_bdrk_01Coxcmvf8KJmEs6oc5srejv',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_19"}',
							name: 'send_message',
						},
						id: 'toolu_bdrk_01LsT4KHKtQYzqMWqbdW5EaQ',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_174',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01Coxcmvf8KJmEs6oc5srejv',
			},
			{
				content: 'synthetic_text_175',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01LsT4KHKtQYzqMWqbdW5EaQ',
			},
		],
		id: 7789,
		signature: 'SIG_357',
	},
	// [TR #6313] openai-chat::content:absent | tool_calls:none
	{
		data: [
			{
				role: 'assistant',
			},
		],
		id: 6313,
		signature: 'SIG_358',
	},
	// [TR #7025] openai-chat::content:absent | tool_calls:2 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning: 'synthetic_text_325',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_20"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-ba8c8e149a99985e',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_21"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-80e924ef5fb421a1',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_176',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-ba8c8e149a99985e',
			},
			{
				content: 'synthetic_text_177',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-80e924ef5fb421a1',
			},
		],
		id: 7025,
		signature: 'SIG_359',
	},
	// [TR #15765] openai-chat::content:string | tool_calls:none | reasoning:[reasoning_content]
	{
		data: [
			{
				content: 'synthetic_text_178',
				reasoning_content: 'synthetic_text_317',
				role: 'assistant',
			},
		],
		id: 15765,
		signature: 'SIG_360',
	},
	// [TR #7077] openai-chat::content:string | tool_calls:1 | reasoning:[reasoning] → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_179',
				reasoning: 'synthetic_text_326',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_22"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-a0785ab401ba3c0f',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_180',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-a0785ab401ba3c0f',
			},
		],
		id: 7077,
		signature: 'SIG_361',
	},
	// [TR #15769] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning_content] → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				reasoning_content: 'synthetic_text_318',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_23"}',
							name: 'send_message',
						},
						id: 'send_message:103',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_181',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'send_message:103',
			},
		],
		id: 15769,
		signature: 'SIG_362',
	},
	// [TR #13644] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				content: 'synthetic_text_182',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_24"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01QYaEwGCWHFsaCYaxEWEwzi',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_25"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01KFLrsuAeneK9gibQPipvhF',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_183',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01QYaEwGCWHFsaCYaxEWEwzi',
			},
			{
				content: 'synthetic_text_184',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01KFLrsuAeneK9gibQPipvhF',
			},
		],
		id: 13644,
		signature: 'SIG_363',
	},
	// [TR #13636] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_26"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01JT6RzXzUzSvfAfMHAXbaCn',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_27"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01RxfShXaGviuXWhWaYehoM7',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_28"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01Hb59XFrj88X5tV3LSWZLjo',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_185',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01JT6RzXzUzSvfAfMHAXbaCn',
			},
			{
				content: 'synthetic_text_186',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01RxfShXaGviuXWhWaYehoM7',
			},
			{
				content: 'synthetic_text_187',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Hb59XFrj88X5tV3LSWZLjo',
			},
		],
		id: 13636,
		signature: 'SIG_364',
	},
	// [TR #16262] openai-chat::content:string | tool_calls:1 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_188',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_29"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_014rc5VaVFVqkravNFj4miZx',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_014rc5VaVFVqkravNFj4miZx',
			},
		],
		id: 16262,
		signature: 'SIG_365',
	},
	// [TR #6543] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_189',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_30"}',
							name: 'web_search',
						},
						id: 'toolu_bdrk_013ULhH5SDBKURkCBJeJ7xC1',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_31"}',
							name: 'web_search',
						},
						id: 'toolu_bdrk_01AXc1wVSpScqqS6N1tzXdyR',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_32"}',
							name: 'send_message',
						},
						id: 'toolu_bdrk_018cHNEK3jf5ks1L1iT4VTw5',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_190',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_013ULhH5SDBKURkCBJeJ7xC1',
			},
			{
				content: 'synthetic_text_191',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01AXc1wVSpScqqS6N1tzXdyR',
			},
			{
				content: 'synthetic_text_192',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_018cHNEK3jf5ks1L1iT4VTw5',
			},
		],
		id: 6543,
		signature: 'SIG_366',
	},
	// [TR #7019] openai-chat::content:absent | tool_calls:none | reasoning:[reasoning]
	{
		data: [
			{
				reasoning: 'synthetic_text_327',
				role: 'assistant',
			},
		],
		id: 7019,
		signature: 'SIG_367',
	},
	// [TR #7668] openai-chat::content:absent | tool_calls:3 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning: 'synthetic_text_328',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_33"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-8fdf272ad34c9799',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_34"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-8980801fa3c7edc8',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_35"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-bc032763339c0b2c',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_193',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-8fdf272ad34c9799',
			},
			{
				content: 'synthetic_text_194',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-8980801fa3c7edc8',
			},
			{
				content: 'synthetic_text_195',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-bc032763339c0b2c',
			},
		],
		id: 7668,
		signature: 'SIG_368',
	},
	// [TR #6090] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_36"}',
							name: 'bash',
						},
						id: 'toolu_bdrk_01UMuNkd6aKEyYMq3MtWSehK',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_37"}',
							name: 'bash',
						},
						id: 'toolu_bdrk_01E9N4H8yGz6rDJ6FWfj3c3u',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_196',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01UMuNkd6aKEyYMq3MtWSehK',
			},
			{
				content: 'synthetic_text_197',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01E9N4H8yGz6rDJ6FWfj3c3u',
			},
		],
		id: 6090,
		signature: 'SIG_369',
	},
	// [TR #9407] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_38"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01SLAtkoxeKr9KCt6VutbUz8',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_39"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_013NGYBerbSf129teFnR4j8y',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_198',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01SLAtkoxeKr9KCt6VutbUz8',
			},
			{
				content: 'synthetic_text_199',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_013NGYBerbSf129teFnR4j8y',
			},
		],
		id: 9407,
		signature: 'SIG_370',
	},
	// [TR #6340] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_200',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_40"}',
							name: 'send_message',
						},
						id: 'toolu_0135AGceAkMqWQPUzCu5oaLq',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_41"}',
							name: 'web_search',
						},
						id: 'toolu_01V7kt8EAwgn33SWio9A1Kh4',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_201',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_0135AGceAkMqWQPUzCu5oaLq',
			},
			{
				content: 'synthetic_text_202',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01V7kt8EAwgn33SWio9A1Kh4',
			},
		],
		id: 6340,
		signature: 'SIG_371',
	},
	// [TR #7069] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning] → tool_content:string | rfu:number:1
	{
		data: [
			{
				reasoning: 'synthetic_text_329',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_42"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-b2f1582e44c7fd03',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_203',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-b2f1582e44c7fd03',
			},
		],
		id: 7069,
		signature: 'SIG_372',
	},
	// [TR #8117] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_204',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_43"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01LoWy2JrPUtdp3RBCEUBMNg',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_44"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01FCXW6kCFbcN4HPgLi96gd3',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_205',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01LoWy2JrPUtdp3RBCEUBMNg',
			},
			{
				content: 'synthetic_text_206',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01FCXW6kCFbcN4HPgLi96gd3',
			},
		],
		id: 8117,
		signature: 'SIG_373',
	},
	// [TR #10408] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_45"}',
							name: 'bash',
						},
						id: 'toolu_01EBjVu8Y5tV9q9jXf7J8rpQ',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_46"}',
							name: 'bash',
						},
						id: 'toolu_01U7zJs5z3TJmktZHiRbVLHm',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_47"}',
							name: 'bash',
						},
						id: 'toolu_01Tx95GAe1SWMn5SbL9hbvsN',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_207',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01EBjVu8Y5tV9q9jXf7J8rpQ',
			},
			{
				content: 'synthetic_text_208',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01U7zJs5z3TJmktZHiRbVLHm',
			},
			{
				content: 'synthetic_text_209',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01Tx95GAe1SWMn5SbL9hbvsN',
			},
		],
		id: 10408,
		signature: 'SIG_374',
	},
	// [TR #14752] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_210',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_48"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01Ka4tsh99oTHBgWt3sxKYLg',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_49"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_019jUGBE8w1g9PKwrCJfEnSS',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_211',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Ka4tsh99oTHBgWt3sxKYLg',
			},
			{
				content: 'synthetic_text_212',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_019jUGBE8w1g9PKwrCJfEnSS',
			},
		],
		id: 14752,
		signature: 'SIG_375',
	},
	// [TR #33] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_213',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_50"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01SgZtFWLZgf7STP1pmYG3US',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_51"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_017i5zCVZP6KxnMqbM4EKpnt',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_214',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01SgZtFWLZgf7STP1pmYG3US',
			},
			{
				content: 'synthetic_text_215',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_017i5zCVZP6KxnMqbM4EKpnt',
			},
		],
		id: 33,
		signature: 'SIG_376',
	},
	// [TR #8197] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_52"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01L7h83739AeDv8BZEzL8cu1',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_53"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01GoP1igH3PCnuMFURRtyFyU',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_54"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_014yGMVKYWYuXUgJNAZTfvbm',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_216',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01L7h83739AeDv8BZEzL8cu1',
			},
			{
				content: 'synthetic_text_217',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01GoP1igH3PCnuMFURRtyFyU',
			},
			{
				content: 'synthetic_text_218',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_014yGMVKYWYuXUgJNAZTfvbm',
			},
		],
		id: 8197,
		signature: 'SIG_377',
	},
	// [TR #16] openai-chat::content:string | tool_calls:none | reasoning:[reasoning_opaque]
	{
		data: [
			{
				content: 'synthetic_text_219',
				reasoning_opaque: 'OPAQUE_315',
				role: 'assistant',
			},
		],
		id: 16,
		signature: 'SIG_378',
	},
	// [TR #13459] openai-chat::content:string | tool_calls:4 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_220',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_55"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01BmzDBRyuzGKdeoDAsmGEv7',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_56"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_017DtBQSw38aqNmWjwiXLZuB',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_57"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01VG5qmwTyBkHZhxBsbWEY7P',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_58"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01H8FUTdk9BMSdan3WLSTert',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_221',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01BmzDBRyuzGKdeoDAsmGEv7',
			},
			{
				content: 'synthetic_text_222',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_017DtBQSw38aqNmWjwiXLZuB',
			},
			{
				content: 'synthetic_text_223',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01VG5qmwTyBkHZhxBsbWEY7P',
			},
			{
				content: 'synthetic_text_224',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01H8FUTdk9BMSdan3WLSTert',
			},
		],
		id: 13459,
		signature: 'SIG_379',
	},
	// [TR #18381] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_225',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_59"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_011LEFknvt3iadfyHsvoaPdj',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_60"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01WSps8PdDz4Q1sZRySpXzPq',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_61"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01Vfea49eENiMBJyg64ZPXN6',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_226',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_011LEFknvt3iadfyHsvoaPdj',
			},
			{
				content: 'synthetic_text_227',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01WSps8PdDz4Q1sZRySpXzPq',
			},
			{
				content: 'synthetic_text_228',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Vfea49eENiMBJyg64ZPXN6',
			},
		],
		id: 18381,
		signature: 'SIG_380',
	},
	// [TR #7686] openai-chat::content:absent | tool_calls:2 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				reasoning: 'synthetic_text_330',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_62"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-bc133d4536470805',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_63"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-b1f3ca0ff7fdb1b7',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_229',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-bc133d4536470805',
			},
			{
				content: 'synthetic_text_230',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-b1f3ca0ff7fdb1b7',
			},
		],
		id: 7686,
		signature: 'SIG_381',
	},
	// [TR #8114] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_231',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_64"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_011AnPYwMKfSyV5kse6FmbJW',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_65"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01VBdxuXUQrKx7x92NTDagWv',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_66"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01MTuRGEyiu4X63PfVHz6Prx',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_232',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_011AnPYwMKfSyV5kse6FmbJW',
			},
			{
				content: 'synthetic_text_233',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01VBdxuXUQrKx7x92NTDagWv',
			},
			{
				content: 'synthetic_text_234',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01MTuRGEyiu4X63PfVHz6Prx',
			},
		],
		id: 8114,
		signature: 'SIG_382',
	},
	// [TR #14031] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_67"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01EqEc9X1YZSXp9Kqkwx5QDY',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_68"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01ECnzyAYZn89zD9oASKHgf9',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_235',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01EqEc9X1YZSXp9Kqkwx5QDY',
			},
			{
				content: 'synthetic_text_236',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01ECnzyAYZn89zD9oASKHgf9',
			},
		],
		id: 14031,
		signature: 'SIG_383',
	},
	// [TR #16418] openai-chat::content:absent | tool_calls:1 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_69"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01RJLVKY62oaPTMixzNHv1Wp',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01RJLVKY62oaPTMixzNHv1Wp',
			},
		],
		id: 16418,
		signature: 'SIG_384',
	},
	// [TR #17] openai-chat::content:absent | tool_calls:1 | extra:[padding] → tool_content:string | rfu:number:0 → content:empty-string | tool_calls:none | extra:[padding]
	{
		data: [
			{
				padding: 'PAD_334',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_70"}',
							name: 'send_message',
						},
						id: 'call_HZy1Lv530rcDgYo3ZxurqUrk',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_237',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'call_HZy1Lv530rcDgYo3ZxurqUrk',
			},
			{
				content: '',
				padding: 'PAD_335',
				role: 'assistant',
			},
		],
		id: 17,
		signature: 'SIG_385',
	},
	// [TR #11471] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:0
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_71"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01RioxhVVzKXmeaZz3ZNzF2R',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_72"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01TWE2GwukHqNwYegSEEPkmt',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_238',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01RioxhVVzKXmeaZz3ZNzF2R',
			},
			{
				content: 'synthetic_text_239',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01TWE2GwukHqNwYegSEEPkmt',
			},
		],
		id: 11471,
		signature: 'SIG_386',
	},
	// [TR #13461] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				content: 'synthetic_text_240',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_73"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01646XWEEdby1FyBLtwEdQy4',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_74"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_013C954fYpLWrfAUe7Jk3T4d',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_241',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01646XWEEdby1FyBLtwEdQy4',
			},
			{
				content: 'synthetic_text_242',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_013C954fYpLWrfAUe7Jk3T4d',
			},
		],
		id: 13461,
		signature: 'SIG_387',
	},
	// [TR #16422] openai-chat::content:string | tool_calls:2 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_243',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_75"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01BmxsB9CKNH6JZexp4oxjBF',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_76"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01NSTCFFi2E3jdneg7PcLVib',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01BmxsB9CKNH6JZexp4oxjBF',
			},
			{
				content: 'synthetic_text_244',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01NSTCFFi2E3jdneg7PcLVib',
			},
		],
		id: 16422,
		signature: 'SIG_388',
	},
	// [TR #6640] openai-chat::content:string | tool_calls:4 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_245',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_77"}',
							name: 'web_search',
						},
						id: 'toolu_01YY2JSBVLi5311CDsfWvJ8q',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_78"}',
							name: 'web_search',
						},
						id: 'toolu_01CBDVeizUkZfYjV6KEVxjL6',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_79"}',
							name: 'bash',
						},
						id: 'toolu_01FojrEWWihmF6M84Y2pfhq1',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_80"}',
							name: 'send_message',
						},
						id: 'toolu_01DwM9wZxZhUfsy51teA9dUc',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_246',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01YY2JSBVLi5311CDsfWvJ8q',
			},
			{
				content: 'synthetic_text_247',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01CBDVeizUkZfYjV6KEVxjL6',
			},
			{
				content: 'synthetic_text_248',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01FojrEWWihmF6M84Y2pfhq1',
			},
			{
				content: 'synthetic_text_249',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_01DwM9wZxZhUfsy51teA9dUc',
			},
		],
		id: 6640,
		signature: 'SIG_389',
	},
	// [TR #7052] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning] | tc_malformed_args → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning: 'synthetic_text_331',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_81"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-bddb402b15a5f2c7',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_250',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-bddb402b15a5f2c7',
			},
		],
		id: 7052,
		signature: 'SIG_390',
	},
	// [TR #7248] openai-chat::content:absent | tool_calls:2 | reasoning:[reasoning] → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning: 'synthetic_text_332',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_82"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-a12c35ece8f8dbb2',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_83"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-abaaeaa3839b7067',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_251',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-a12c35ece8f8dbb2',
			},
			{
				content: 'synthetic_text_252',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-abaaeaa3839b7067',
			},
		],
		id: 7248,
		signature: 'SIG_391',
	},
	// [TR #15788] openai-chat::content:absent | tool_calls:none | reasoning:[reasoning_content]
	{
		data: [
			{
				reasoning_content: 'synthetic_text_319',
				role: 'assistant',
			},
		],
		id: 15788,
		signature: 'SIG_392',
	},
	// [TR #16046] openai-chat::content:absent | tool_calls:2 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_84"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_016drYLHShKRBsLpooXEUnxW',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_85"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01W87aLyDnaWEqy8WngBeXvj',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_016drYLHShKRBsLpooXEUnxW',
			},
			{
				content: 'synthetic_text_253',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01W87aLyDnaWEqy8WngBeXvj',
			},
		],
		id: 16046,
		signature: 'SIG_393',
	},
	// [TR #15] openai-chat::content:empty-string | tool_calls:1 | reasoning:[reasoning_text,reasoning_opaque] | tc_extra:[index] → tool_content:string | rfu:number:0 → content:empty-string | tool_calls:none | reasoning:[reasoning_text]
	{
		data: [
			{
				content: '',
				reasoning_opaque: 'OPAQUE_316',
				reasoning_text: 'synthetic_text_321',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_86"}',
							name: 'send_message',
						},
						id: 'call_MHxpNVV3OUo3ak8yT0hlaTE1bTY',
						index: 0,
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_254',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'call_MHxpNVV3OUo3ak8yT0hlaTE1bTY',
			},
			{
				content: '',
				reasoning_text: 'synthetic_text_322',
				role: 'assistant',
			},
		],
		id: 15,
		signature: 'SIG_394',
	},
	// [TR #1735] openai-chat::content:string | tool_calls:1 | tc_malformed_args → tool_content:string | rfu:number:0
	{
		data: [
			{
				content: 'synthetic_text_255',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_87"}',
							name: 'send_message',
						},
						id: 'toolu_bdrk_01JaxrxFtQgQUAMV7A52Nser',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_256',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_bdrk_01JaxrxFtQgQUAMV7A52Nser',
			},
		],
		id: 1735,
		signature: 'SIG_395',
	},
	// [TR #7701] openai-chat::content:absent | tool_calls:4 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
	{
		data: [
			{
				reasoning: 'synthetic_text_333',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_88"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-b2bdec3d7fbe8c18',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_89"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-b7863a852e3279ca',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_90"}',
							name: 'web_search',
						},
						id: 'chatcmpl-tool-876820e547a0bb6e',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_91"}',
							name: 'send_message',
						},
						id: 'chatcmpl-tool-80cebfda4c0abf0b',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_257',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-b2bdec3d7fbe8c18',
			},
			{
				content: 'synthetic_text_258',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-b7863a852e3279ca',
			},
			{
				content: 'synthetic_text_259',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-876820e547a0bb6e',
			},
			{
				content: 'synthetic_text_260',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'chatcmpl-tool-80cebfda4c0abf0b',
			},
		],
		id: 7701,
		signature: 'SIG_396',
	},
	// [TR #9409] openai-chat::content:string | tool_calls:6 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_261',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_92"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_017AXFgSyUL3wNQN6ZDsbv5M',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_93"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01Hv6J2ZPPuLCh6SjRbcgy2Y',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_94"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01BFfRHqhCQE19Aie7i3k6h8',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_95"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_011PwuVVcJcCxin5yus5a3Lb',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_96"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01X6JYLWGZKA4yx3ZtEJe6eF',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_97"}',
							name: 'web_search',
						},
						id: 'toolu_vrtx_01BAfSbcuhMQnBdiAnjCojA2',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_262',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_017AXFgSyUL3wNQN6ZDsbv5M',
			},
			{
				content: 'synthetic_text_263',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Hv6J2ZPPuLCh6SjRbcgy2Y',
			},
			{
				content: 'synthetic_text_264',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01BFfRHqhCQE19Aie7i3k6h8',
			},
			{
				content: 'synthetic_text_265',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_011PwuVVcJcCxin5yus5a3Lb',
			},
			{
				content: 'synthetic_text_266',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01X6JYLWGZKA4yx3ZtEJe6eF',
			},
			{
				content: 'synthetic_text_267',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01BAfSbcuhMQnBdiAnjCojA2',
			},
		],
		id: 9409,
		signature: 'SIG_397',
	},
	// [TR #10094] openai-chat::content:string | tool_calls:6 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_268',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_98"}',
							name: 'bash',
						},
						id: 'toolu_01ShNbYAKx25d8zaUBvFNoHJ',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_99"}',
							name: 'bash',
						},
						id: 'toolu_01S1SstmWt78is1bNgN5NnCw',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_100"}',
							name: 'bash',
						},
						id: 'toolu_01LAn147VARj4Nfz8fFGX1zt',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_101"}',
							name: 'bash',
						},
						id: 'toolu_01GXNrkgZtX5EVTH4DqyySmf',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_102"}',
							name: 'bash',
						},
						id: 'toolu_01EWVhn3mJVmL8Eh4xbdXKds',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_103"}',
							name: 'bash',
						},
						id: 'toolu_01AoSJ5zq15LsMcpbAByGbUS',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_269',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01ShNbYAKx25d8zaUBvFNoHJ',
			},
			{
				content: 'synthetic_text_270',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01S1SstmWt78is1bNgN5NnCw',
			},
			{
				content: 'synthetic_text_271',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01LAn147VARj4Nfz8fFGX1zt',
			},
			{
				content: 'synthetic_text_272',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01GXNrkgZtX5EVTH4DqyySmf',
			},
			{
				content: 'synthetic_text_273',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01EWVhn3mJVmL8Eh4xbdXKds',
			},
			{
				content: 'synthetic_text_274',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01AoSJ5zq15LsMcpbAByGbUS',
			},
		],
		id: 10094,
		signature: 'SIG_398',
	},
	// [TR #10095] openai-chat::content:string | tool_calls:8 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_275',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_104"}',
							name: 'bash',
						},
						id: 'toolu_01UrHyYpdHtu7BDMJkwh2QRA',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_105"}',
							name: 'bash',
						},
						id: 'toolu_014RKws9xyBNCFH2qf253Xs3',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_106"}',
							name: 'bash',
						},
						id: 'toolu_0141N6qqWnD2QUUqugswbWLJ',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_107"}',
							name: 'bash',
						},
						id: 'toolu_01G21K3oiZ6gmxm4oRETnanL',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_108"}',
							name: 'bash',
						},
						id: 'toolu_015taZ8EsE3mUFqkfjqASDRy',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_109"}',
							name: 'bash',
						},
						id: 'toolu_01FqEemeCCd9LsrcA7GSDynY',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_110"}',
							name: 'bash',
						},
						id: 'toolu_012pLBFsVm1AQMHnWVsWtETE',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_111"}',
							name: 'bash',
						},
						id: 'toolu_01PjjzXSC85xEFUjUNBAWYnh',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_276',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01UrHyYpdHtu7BDMJkwh2QRA',
			},
			{
				content: 'synthetic_text_277',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_014RKws9xyBNCFH2qf253Xs3',
			},
			{
				content: 'synthetic_text_278',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_0141N6qqWnD2QUUqugswbWLJ',
			},
			{
				content: 'synthetic_text_279',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01G21K3oiZ6gmxm4oRETnanL',
			},
			{
				content: 'synthetic_text_280',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_015taZ8EsE3mUFqkfjqASDRy',
			},
			{
				content: 'synthetic_text_281',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01FqEemeCCd9LsrcA7GSDynY',
			},
			{
				content: 'synthetic_text_282',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_012pLBFsVm1AQMHnWVsWtETE',
			},
			{
				content: 'synthetic_text_283',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01PjjzXSC85xEFUjUNBAWYnh',
			},
		],
		id: 10095,
		signature: 'SIG_399',
	},
	// [TR #10367] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_112"}',
							name: 'send_message',
						},
						id: 'toolu_01GxoASH7dgnC1RGZVXzAxXe',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_113"}',
							name: 'web_search',
						},
						id: 'toolu_013t3AbYiVviBL4ZnypvKdBz',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_114"}',
							name: 'web_search',
						},
						id: 'toolu_01M7v1UeTBPePp8DoNMe9SNC',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_284',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_01GxoASH7dgnC1RGZVXzAxXe',
			},
			{
				content: 'synthetic_text_285',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_013t3AbYiVviBL4ZnypvKdBz',
			},
			{
				content: 'synthetic_text_286',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01M7v1UeTBPePp8DoNMe9SNC',
			},
		],
		id: 10367,
		signature: 'SIG_400',
	},
	// [TR #10407] openai-chat::content:absent | tool_calls:4 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_115"}',
							name: 'send_message',
						},
						id: 'toolu_01DPW63JB25TybNsMxP52LtT',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_116"}',
							name: 'web_search',
						},
						id: 'toolu_019vYpR6krxBW3DkoiY2mxGV',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_117"}',
							name: 'bash',
						},
						id: 'toolu_01WnxEw9suuyF2HQHxQJRW1u',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_118"}',
							name: 'bash',
						},
						id: 'toolu_01HCgRPKfSuUv6H3sRYC6Czr',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_287',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_01DPW63JB25TybNsMxP52LtT',
			},
			{
				content: 'synthetic_text_288',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_019vYpR6krxBW3DkoiY2mxGV',
			},
			{
				content: 'synthetic_text_289',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01WnxEw9suuyF2HQHxQJRW1u',
			},
			{
				content: 'synthetic_text_290',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_01HCgRPKfSuUv6H3sRYC6Czr',
			},
		],
		id: 10407,
		signature: 'SIG_401',
	},
	// [TR #13071] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
	{
		data: [
			{
				content: 'synthetic_text_291',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_119"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01SUz4xfcLbDnA4QDZDXxYNy',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_120"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_016uQm6ivjBXaGoP6JivxkJb',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_121"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01AFDvjNQ1UaREareEzEjwH9',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_292',
				requiresFollowUp: 0,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01SUz4xfcLbDnA4QDZDXxYNy',
			},
			{
				content: 'synthetic_text_293',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_016uQm6ivjBXaGoP6JivxkJb',
			},
			{
				content: 'synthetic_text_294',
				requiresFollowUp: 1,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01AFDvjNQ1UaREareEzEjwH9',
			},
		],
		id: 13071,
		signature: 'SIG_402',
	},
	// [TR #14484] openai-chat::content:string | tool_calls:5 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_295',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_122"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_019yDngzNQP7Z8YGQx4pFute',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_123"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_015MJq1quaXeqG9JY1j1kJNz',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_124"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_018pdPsVT2Y56hdoSdT2uGG7',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_125"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_014nocQfZr1GtzELpzSVmZBT',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_126"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_016f41FK6msUPGKz26TFT84S',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_296',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_019yDngzNQP7Z8YGQx4pFute',
			},
			{
				content: 'synthetic_text_297',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_015MJq1quaXeqG9JY1j1kJNz',
			},
			{
				content: 'synthetic_text_298',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_018pdPsVT2Y56hdoSdT2uGG7',
			},
			{
				content: 'synthetic_text_299',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_014nocQfZr1GtzELpzSVmZBT',
			},
			{
				content: 'synthetic_text_300',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_016f41FK6msUPGKz26TFT84S',
			},
		],
		id: 14484,
		signature: 'SIG_403',
	},
	// [TR #14645] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_127"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01YBhgv1MRdxLJPucUY7SSLS',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_128"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01Ppcmqu2Pq8p7Hpk5RkZLUg',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_301',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01YBhgv1MRdxLJPucUY7SSLS',
			},
			{
				content: 'synthetic_text_302',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Ppcmqu2Pq8p7Hpk5RkZLUg',
			},
		],
		id: 14645,
		signature: 'SIG_404',
	},
	// [TR #14650] openai-chat::content:absent | tool_calls:4 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_129"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01PjqftQTsRBcmuZYH8fe85B',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_130"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01985FQoFLtTvPUgZ9yEWPzs',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_131"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01BGRvMvQhQzSxCNCez2TNFS',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_132"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_01PineVekLFt6zw2533XZ3yr',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_303',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01PjqftQTsRBcmuZYH8fe85B',
			},
			{
				content: 'synthetic_text_304',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01985FQoFLtTvPUgZ9yEWPzs',
			},
			{
				content: 'synthetic_text_305',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01BGRvMvQhQzSxCNCez2TNFS',
			},
			{
				content: 'synthetic_text_306',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01PineVekLFt6zw2533XZ3yr',
			},
		],
		id: 14650,
		signature: 'SIG_405',
	},
	// [TR #14810] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_133"}',
							name: 'send_message',
						},
						id: 'toolu_vrtx_013JHsYEBrpMacacwdbuFikq',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_134"}',
							name: 'bash',
						},
						id: 'toolu_vrtx_01Y9pAFqNCjoHX5HTHnmyzsw',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_307',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_013JHsYEBrpMacacwdbuFikq',
			},
			{
				content: 'synthetic_text_308',
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Y9pAFqNCjoHX5HTHnmyzsw',
			},
		],
		id: 14810,
		signature: 'SIG_406',
	},
	// [TR #15775] openai-chat::content:string | tool_calls:1 | reasoning:[reasoning_content] → tool_content:string | rfu:boolean:false
	{
		data: [
			{
				content: 'synthetic_text_309',
				reasoning_content: 'synthetic_text_320',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_135"}',
							name: 'send_message',
						},
						id: 'send_message:104',
						type: 'function',
					},
				],
			},
			{
				content: 'synthetic_text_310',
				requiresFollowUp: false,
				role: 'tool',
				tool_call_id: 'send_message:104',
			},
		],
		id: 15775,
		signature: 'SIG_407',
	},
	// [TR #16420] openai-chat::content:absent | tool_calls:3 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_136"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_019F4RwREYgMftrTKyDnAp2v',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_137"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01Ftyi5iExbjCewDQeXG8KZy',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_138"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_011buAwbGoQ4taMQazgo4zhk',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_019F4RwREYgMftrTKyDnAp2v',
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01Ftyi5iExbjCewDQeXG8KZy',
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_011buAwbGoQ4taMQazgo4zhk',
			},
		],
		id: 16420,
		signature: 'SIG_408',
	},
	// [TR #16427] openai-chat::content:absent | tool_calls:4 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
	{
		data: [
			{
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_139"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01UpVCZJDksnPscS8mS3Nwz3',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_140"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01BSeamKg21Dk7Lnd6VNXEcm',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_141"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_012wWvXzyvAT4f57UH4XMBWJ',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_142"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01QBVmUT9PNpTBPv3djc3DjJ',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01UpVCZJDksnPscS8mS3Nwz3',
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01BSeamKg21Dk7Lnd6VNXEcm',
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_012wWvXzyvAT4f57UH4XMBWJ',
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01QBVmUT9PNpTBPv3djc3DjJ',
			},
		],
		id: 16427,
		signature: 'SIG_409',
	},
	// [TR #19962] openai-chat::content:string | tool_calls:2 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
	{
		data: [
			{
				content: 'synthetic_text_311',
				role: 'assistant',
				tool_calls: [
					{
						function: {
							arguments: '{"key":"value_143"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01XoKg9opxi8GSV28ugF9DsZ',
						type: 'function',
					},
					{
						function: {
							arguments: '{"key":"value_144"}',
							name: 'read_image',
						},
						id: 'toolu_vrtx_01NZ3S4ubvZWpkseUMjB94zp',
						type: 'function',
					},
				],
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01XoKg9opxi8GSV28ugF9DsZ',
			},
			{
				content: [
					{
						detail: 'high',
						image_url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
						type: 'input_image',
					},
				],
				requiresFollowUp: true,
				role: 'tool',
				tool_call_id: 'toolu_vrtx_01NZ3S4ubvZWpkseUMjB94zp',
			},
		],
		id: 19962,
		signature: 'SIG_410',
	},
]

export const responsesFixtures: Fixture<ResponsesDataItem>[] = [
	// [TR #1288] responses::content:array | blocks:[output_text] | tool_calls:none | extra:[type] → type:function_call | fc_extra:[status] → type:function_call_output | output:string | rfu:number:0
	{
		data: [
			{
				content: [
					{
						text: 'synthetic_text_312',
						type: 'output_text',
					},
				],
				role: 'assistant',
				type: 'message',
			},
			{
				arguments: '{"key":"value_145"}',
				call_id: 'toolu_bdrk_01DH4pwrufMrXcymPDKMnFBS',
				name: 'send_message',
				status: 'completed',
				type: 'function_call',
			},
			{
				call_id: 'toolu_bdrk_01DH4pwrufMrXcymPDKMnFBS',
				output: '{"key":"value_336"}',
				requiresFollowUp: 0,
				type: 'function_call_output',
			},
		],
		id: 1288,
		signature: 'SIG_411',
	},
	// [TR #1176] responses::type:function_call | fc_extra:[id,status] → type:function_call_output | output:string | rfu:number:0
	{
		data: [
			{
				arguments: '{"key":"value_146"}',
				call_id: 'call_Pj8NSw6VJj7f1eGKbrdvjRfc',
				id: '26e8+mo9tDZkiOzTJzK+qH+oaz45N6Lz9x5ZBLiAKBdM2qBEBWnEnaVfDs3looQ7tR4T0gAmLDDrLLsz2sS7gvaRCAylrGOSCDmhzaDGpkglTzkrh53Enj+ENCwo0feF+vZf/+kq3eu6BaYFlFFDbL5+uHvZhaxXWJXfIjzslUJ9YnedJvgb6GHsnZOvkYbjDJerUXD7...TRUNCATED...NirKN0Eq1Y2uIgnnxD1xxvttCQe/O8bdClotGLgqm/U9aT8w==',
				name: 'send_message',
				status: 'completed',
				type: 'function_call',
			},
			{
				call_id: 'call_Pj8NSw6VJj7f1eGKbrdvjRfc',
				output: '{"key":"value_337"}',
				requiresFollowUp: 0,
				type: 'function_call_output',
			},
		],
		id: 1176,
		signature: 'SIG_412',
	},
	// [TR #1316] responses::
	{
		data: [],
		id: 1316,
		signature: 'SIG_413',
	},
	// [TR #1282] responses::content:array | blocks:[output_text] | tool_calls:none | extra:[type]
	{
		data: [
			{
				content: [
					{
						text: 'synthetic_text_313',
						type: 'output_text',
					},
				],
				role: 'assistant',
				type: 'message',
			},
		],
		id: 1282,
		signature: 'SIG_414',
	},
	// [TR #1283] responses::type:function_call | fc_extra:[status] → type:function_call_output | output:string | rfu:number:0
	{
		data: [
			{
				arguments: '{"key":"value_147"}',
				call_id: 'toolu_bdrk_016VWhpvMC1ugdhEUFr6KHiC',
				name: 'send_message',
				status: 'completed',
				type: 'function_call',
			},
			{
				call_id: 'toolu_bdrk_016VWhpvMC1ugdhEUFr6KHiC',
				output: '{"key":"value_338"}',
				requiresFollowUp: 0,
				type: 'function_call_output',
			},
		],
		id: 1283,
		signature: 'SIG_415',
	},
	// [TR #1197] responses::content:array | blocks:[output_text] | tool_calls:none | extra:[id,phase,status,type] → type:function_call | fc_extra:[id,status] → type:function_call_output | output:string | rfu:number:0
	{
		data: [
			{
				content: [
					{
						annotations: [],
						logprobs: [],
						text: '',
						type: 'output_text',
					},
				],
				id: '5kfUBU/MSQ978/YDk74tyfKOkY6VIR2uJEVhifV65CskmNNVR4vGvRHNVZ9ybVpvinxWc5SSt8BZryZW30xl6JljQtKaNIlzMhOuL6NONWLPl0bTmtEt6xE2rSxVGqptPbUNtv7ox1Uy02zBybIms0wu79dPgGoKuRYArAhTyoKukMoJrvhVeNN5z7loFRyQfsFW5P1l...TRUNCATED...Pj3cCCjJToiDMhrAFy2U0sd2PkkBjGpJs21n5qOBknF4gQWHU=',
				phase: 'commentary',
				role: 'assistant',
				status: 'completed',
				type: 'message',
			},
			{
				arguments: '{"key":"value_148"}',
				call_id: 'call_UyaVfJCZfffRel6wZxELExqQ',
				id: 'RndwbHL+bhFvg0apogwHtoyKSoQOEtm7W/mlcLfsMYHGKEqpDSmsJeX/s5TprcSmYJrqzEUr9SiQTJFOmX+Z1tsg6PAJ8+SqensYmVNJldNGGoESPOIWzUUQI5Mxd/T99leSlKFtJ6RF/Rr6TlM1bsn8dTrymeqfzBhDUQbVGv2nDPrHv8xorrnsl3UYnXPeONKeqQti...TRUNCATED...s4qmFrx5eat3jB9ZKx6hSEWdz5e5q2+tFlQSqxbSZTj+UTgg==',
				name: 'send_message',
				status: 'completed',
				type: 'function_call',
			},
			{
				call_id: 'call_UyaVfJCZfffRel6wZxELExqQ',
				output: '{"key":"value_339"}',
				requiresFollowUp: 0,
				type: 'function_call_output',
			},
		],
		id: 1197,
		signature: 'SIG_416',
	},
]
